language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install select
  - pip install socket
  - pip install signal
  - pip install pickle
  - pip install struct
  - pip install argparse
# command to run tests
script:
  - python ./server.py&
  - python ./client.py&
  - sleep 5
  - python ./test.py
  - pytest # or py.test for Python versions 3.5 and below
